export type Sizes = 'sm' | 'md' | 'lg'

export type Borders = 'solid' | 'dashed' | 'dotted' | 'none'

export type StatusVariants =
  | 'pending'
  | 'primary'
  | 'success'
  | 'danger'
  | 'warning'
  | 'info'
  | 'pending-light'
  | 'primary-light'
  | 'success-light'
  | 'danger-light'
  | 'warning-light'
  | 'info-light'

export type Variants =
  | 'primary'
  | 'pending'
  | 'success'
  | 'danger'
  | 'warning'
  | 'info'
  | 'magenta'
  | 'volcano'
  | 'cyan'
  | 'geekblue'
  | 'lime'
  | 'gold'
  | 'orange'
  | 'teal'
  | 'skyblue'
  | 'slate'
  | 'purple'
  | 'primary-light'
  | 'pending-light'
  | 'success-light'
  | 'danger-light'
  | 'warning-light'
  | 'info-light'
  | 'magenta-light'
  | 'volcano-light'
  | 'cyan-light'
  | 'geekblue-light'
  | 'lime-light'
  | 'gold-light'
  | 'orange-light'
  | 'teal-light'
  | 'skyblue-light'
  | 'slate-light'
  | 'purple-light'
